PrjD1FW/Models/company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PrjD1FW.Models
{
    public class company
    {


        [DataType(DataType.DateTime)]
        [Display(Name = "Registration Date")]
        public DateTime RegistrationDate { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 6)]
        [Display(Name = "Name")]
        public string Name { get; set; }


        [DataType(DataType.Text)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 6)]
        [Display(Name = "Street")]
        public string Street { get; set; }

        [DataType(DataType.PostalCode)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 4)]
        [Display(Name = "PostalCode")]
        public string zip { get; set; }

        [DataType(DataType.Text)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 2)]
        [Display(Name = "city")]
        public string city { get; set; }

        [DataType(DataType.PhoneNumber)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 4)]
        [Display(Name = "Phone Number")]
        public string tele { get; set; }

        [DataType(DataType.PhoneNumber)]
        [StringLength(100, ErrorMessage = "\"{0}\" muss mind. {2} Zeichen lang sein.", MinimumLength = 4)]
        [Display(Name = "Fax Number")]
        public string fax { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "FK_creator")]
        public int FK_creator { get; set; }

    }
}

PrjD1FW/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PrjD1FW.Models;
using PrjD1FW.Services;

namespace PrjD1FW.Controllers
{
    public class CompaniesController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {

            company company = new company();

            if (TempData["session"] != null)
            {
                AuthedUser authedUser = new AuthedUser();
                authedUser = (AuthedUser)TempData["session"];

                if (authedUser.auth_success == false)
                {
                    return RedirectToAction("notAuthenticated", "error");
                }
                company.FK_creator = authedUser.id;
                return View("RegisterCompany", company);
            }
            else
            {
                return RedirectToAction("Index", "error");
            }
        }

        public ActionResult Register(company company)
        {
            if (ModelState.IsValid)
            {
                SecurityService securityService = new SecurityService();
                ReturnInfo registerCompany = securityService.RegisterCompany(company);

                if (registerCompany.success)
                {
                    ViewData["Message"] = "success";
                    return View("DetailsCompany", company);
                }
                else
                {
                    ViewData["Message"] = registerCompany.errorMessage;
                }
                return View("RegisterCompany", company);
            }
            else
            {
                ViewData["Message"] = "Registration Failed!";
                return View("Register", company);
            }
        }

        public ActionResult ListCompanies()
        {
            var companies = new List<company>()
            {
                new company(){ city = "132312321123", fax = "132312321123", FK_creator = 1, Name = "132312321123", RegistrationDate = DateTime.Now, Street = "132312321123", tele = "1132213", zip ="123123"},
                new company(){ city = "132312321123", fax = "132312321123", FK_creator = 1, Name = "132312321123", RegistrationDate = DateTime.Now, Street = "132312321123", tele = "1132213", zip ="123123"},
                new company(){ city = "132312321123", fax = "132312321123", FK_creator = 1, Name = "132312321123", RegistrationDate = DateTime.Now, Street = "132312321123", tele = "1132213", zip ="123123"},
                new company(){ city = "132312321123", fax = "132312321123", FK_creator = 1, Name = "132312321123", RegistrationDate = DateTime.Now, Street = "132312321123", tele = "1132213", zip ="123123"},

            };

            return View("ListCompanies",companies);
        }
    }
}

PrjD1FW/Views/Companies/Company.cshtml
@model PrjD1FW.Models.company

@{
    ViewBag.Title = "Company";
}

<h2>Company</h2>

<div>
    <h4>company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tele)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tele)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FK_creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FK_creator)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PrjD1FW/Views/Companies/DetailsCompany.cshtml
@model PrjD1FW.Models.company

@{
    ViewBag.Title = "DetailsCompany";
}

<h2>DetailsCompany</h2>

<div>
    <h4>company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tele)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tele)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FK_creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FK_creator)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PrjD1FW/Views/Companies/EditCompany.cshtml
@model PrjD1FW.Models.company

@{
    ViewBag.Title = "EditCompany";
}

<h2>EditCompany</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tele, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tele, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tele, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FK_creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FK_creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PrjD1FW/Views/Companies/ListCompanies.cshtml
@model IEnumerable<PrjD1FW.Models.company>

@{
    ViewBag.Title = "ListCompanies";
}

<h2>ListCompanies</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tele)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FK_creator)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tele)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FK_creator)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

PrjD1FW/Views/Companies/RegisterCompany.cshtml
@model PrjD1FW.Models.company


@{
    ViewBag.Title = "RegisterCompany";
}

<h2>RegisterCompany</h2>


@using (Html.BeginForm("Register", "Companies", FormMethod.Post))
{
    @Html.AntiForgeryToken()


<div class="form-horizontal">
    <h4>company</h4>
    <hr />
    @if (ViewData["Message"] != null)
    {
        <div class="text-danger">
            <p>@ViewData["Message"].ToString()</p>
        </div>
    }


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="form-group">

    @Html.LabelFor(model => model.FK_creator, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.DisplayFor(model => model.FK_creator)
    @Html.HiddenFor(model => model.FK_creator)

</div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.zip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.zip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.zip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tele, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tele, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tele, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fax, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fax, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fax, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}